### ISSUE TITLE
Broken source-maps

### ISSUE THREAD

**Issue by JannikGM** [vite-plugin/vite-plugin-commonjs#28]
I believe this plugin corrupts source-maps.

Chrome devtools will not point at `debugger` statements; I believe this plugin is causing the misalignment in the source-maps.

See https://github.com/vite-plugin/vite-plugin-utils/issues/8 for my speculation as to why that is.

**Comment by caoxiemeihao** [comment]
Thanks for your feedback, I'm not sure exactly where the problem you describe is occurring.
I did currently find one that was breaking the sourcemap and I fixed it.

**Comment by yejimeiming** [comment]
Thanks for your feedback, I'm not sure exactly where the problem you describe is occurring.
I did currently find one that was breaking the sourcemap and I fixed it.

---

`vite-plugin-commonjs` will not break the line number of the source code, it will only insert the corresponding runtime code in the first line or after the source code.

https://github.com/vite-plugin/vite-plugin-commonjs/blob/v0.8.0/test/fixtures/src/dynamic.tsx
<img width="547" alt="image" src="https://github.com/vite-plugin/vite-plugin-commonjs/assets/135394392/2ff51298-fcc5-4ced-842c-4468faef37a3">

https://github.com/vite-plugin/vite-plugin-commonjs/blob/v0.8.0/test/fixtures/__snapshots__/dynamic.tsx
<img width="1133" alt="image" src="https://github.com/vite-plugin/vite-plugin-commonjs/assets/135394392/532b8de9-036b-4225-b174-835e9012311c">

**Comment by caoxiemeihao** [comment]
> Yes, this report is invalid then.

Yeah! I'm not very clear on sourcemap, and I think blindly generating sourcemap would break it, because Vite has already converted the `.js` or `.ts` file once and generated sourcemap,  so if I generate sourcemap again, which is essentially based on Vite's converted  code, it's obviously wrong to do so.

So, I think we should keep the original sourcemap generated by Vite and not generate it again.

**Comment by yejimeiming** [comment]
> Yes, this report is invalid then.

Yeah! I'm not very clear on sourcemap, and I think blindly generating sourcemap would break it, because Vite has already converted the `.js` or `.ts` file once and generated sourcemap,  so if I generate sourcemap again, which is essentially based on Vite's converted  code, it's obviously wrong to do so.

So, I think we should keep the original sourcemap generated by Vite and not generate it again.

**Comment by yejimeiming** [comment]
Thanks for your persistence! I think I may have found the answer in the [Vite source code](https://github.com/vitejs/vite/blob/v4.3.9/packages/vite/src/node/utils.ts#L732-L790).
I'll try to fix this in the next release(v0.8.1 #30) using [magic-string](https://github.com/rich-harris/magic-string).
BTW, explain `vite-plugin-utils/function(MagicString)`, it makes sense because it's very small!
